version: '3.8'

x-var: &COMMON
  networks:
    internal:

networks:
  internal:

services:
  nextjs:
    <<: *COMMON
    build: ../../build
    image: kaduhiro/nextjs
    container_name: nextjs
    hostname: nextjs
    ports:
      - 3000:3000
    volumes:
      - ../..:/app
    environment:
      URL_PREFIX: /out
    command:
      - /bin/sh
      - -c
      - 'yarn && yarn build && yarn export && yarn serve'
