name: GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build Next.js
        run: yarn build
        env:
          URL_PREFIX: /nextjs # if using a custom domain, not required

      - name: Export Next.js
        run: yarn export

      - name: Add nojekyll
        run: touch ./out/.nojekyll

      # - name: Add custom domain
      #   run: echo localhost.localdomain > ./out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
